default_window_size = [
    500.0,
    600.0,
]
auto_save = true

[popped_tabs.Midi]
pos_x = 439.0
pos_y = 631.0
width = 428.0
height = 600.0
collapsed = false

[popped_tabs.Macros]
pos_x = 439.0
pos_y = 632.0
width = 435.0
height = 598.0
collapsed = false

[popped_tabs.Block1]
pos_x = 439.0
pos_y = 1.0
width = 429.0
height = 628.0
collapsed = false

[popped_tabs.Settings]
pos_x = 17.0
pos_y = 464.0
width = 450.0
height = 427.0
collapsed = false

[popped_tabs.Inputs]
pos_x = 21.0
pos_y = 873.0
width = 450.0
height = 394.0
collapsed = false

[popped_tabs.Block3]
pos_x = 1313.0
pos_y = 0.0
width = 432.0
height = 632.0
collapsed = false

[popped_tabs.Presets]
pos_x = 858.0
pos_y = 647.0
width = 442.0
height = 597.0
collapsed = false

[popped_tabs.Block2]
pos_x = 871.0
pos_y = 0.0
width = 441.0
height = 627.0
collapsed = false
